// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-gl1XRf73KMR5ARpNO1I5WiY0ajoXWWQ',
    appId: '1:139062472676:web:7199e09005320df85661f1',
    messagingSenderId: '139062472676',
    projectId: 'testfirebase-13821',
    authDomain: 'testfirebase-13821.firebaseapp.com',
    storageBucket: 'testfirebase-13821.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6mNYGTdw-zuir-xBesgY0ozHm54vKU_o',
    appId: '1:139062472676:android:c1c947dafc5cd8965661f1',
    messagingSenderId: '139062472676',
    projectId: 'testfirebase-13821',
    storageBucket: 'testfirebase-13821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycQOJrodCUdHkW4OsWFnqV7-eRBacwvY',
    appId: '1:139062472676:ios:7abc0dfa54e698a15661f1',
    messagingSenderId: '139062472676',
    projectId: 'testfirebase-13821',
    storageBucket: 'testfirebase-13821.appspot.com',
    iosClientId: '139062472676-baalha7pd9e41sp61j9t7anp2js6tmgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebaseDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycQOJrodCUdHkW4OsWFnqV7-eRBacwvY',
    appId: '1:139062472676:ios:7abc0dfa54e698a15661f1',
    messagingSenderId: '139062472676',
    projectId: 'testfirebase-13821',
    storageBucket: 'testfirebase-13821.appspot.com',
    iosClientId: '139062472676-baalha7pd9e41sp61j9t7anp2js6tmgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebaseDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-gl1XRf73KMR5ARpNO1I5WiY0ajoXWWQ',
    appId: '1:139062472676:web:75457a0e59b7e4ff5661f1',
    messagingSenderId: '139062472676',
    projectId: 'testfirebase-13821',
    authDomain: 'testfirebase-13821.firebaseapp.com',
    storageBucket: 'testfirebase-13821.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB-gl1XRf73KMR5ARpNO1I5WiY0ajoXWWQ',
    appId: '1:139062472676:web:a9361ff14b423a025661f1',
    messagingSenderId: '139062472676',
    projectId: 'testfirebase-13821',
    authDomain: 'testfirebase-13821.firebaseapp.com',
    storageBucket: 'testfirebase-13821.appspot.com',
  );
}
